[net]
git-fetch-with-cli = true   # use the `git` executable for git operations
offline = true              # do not access the network

[term]
verbose = false        # whether cargo provides verbose output
color = 'auto'         # whether cargo colorizes output
progress.when = 'auto' # whether cargo shows progress bar
